### ISSUE TITLE
grasptype data

### ISSUE THREAD

**Issue by ysyf293** [hjlllll/Functionalgrasp#1]
![image](https://github.com/hjlllll/Functionalgrasp/assets/144201362/d2688862-e2ba-4eb1-a60a-fac97d62bec7)
Hello, thank you very much for your excellent work. I need access permission when I obtain the grasptype data set, could you please open it？

**Comment by hjlllll** [comment]
ok, sorry for that, did not check well.

**Comment by ysyf293** [comment]
![image](https://github.com/hjlllll/Functionalgrasp/assets/144201362/f92f1a70-bd9c-465d-a965-e87dcd7fa9f1)
Thank you for your reply. I would like to ask again, for the 20-digit touch code you provided, the first 16 digits are the 16 joints of the dexterous hand, and the last four digits are the intentions. Then how is the functional partition of the object reflected? In other words, when the function of the object is divided into the point cloud, how does each finger correspond to the part of the functional partition?

**Comment by ysyf293** [comment]
Hello, I would like to ask why 128 instances appear 100 times each in the downloaded ’0.002_s420_465-100_ex-True_seg-True_train_record-is111111-new_withlabelgrasp-expanded-100-unsampled.pkl‘ file, I understand that each instance has a grip type label, but there are 12900 in the ’0.002_s420_465-100_ex-True_seg-True_train_record-is111111-new_withlabelgrasp-expanded-100-unsampled.pkl‘  file.

**Comment by ysyf293** [comment]
另外，我还想问一下关于lable_grasps的值的含义，为什么33维数值中有多个1，不应该每一种物体对应一个手势，即某一维为1吗？如能抽空解答，万分感谢！
![image](https://github.com/hjlllll/Functionalgrasp/assets/144201362/8ad5ca5b-0859-47e7-9ecc-56288432dd64)

**Comment by hjlllll** [comment]
Thanks for asking
1.20-bit code is the label of each points on the objects, it can demonstrate the functional relationship between each finger part and each points of pointcloud. It can be seen from paper.
2.12900 you can see it as the expansion during training, just do copy data staff,129 will also be ok.
3. for the grasp type classification, as for the dataset is small, multi-classification not work well, so we treat this problem as the multi-2-classfication problem, which means the network output is [b,33], where the last dim is 1/0, 1 means this object can have this grasp type and 0 means no, and thats why we use BCEloss. And after training, one of these grasp types is randomly chosen as the pre-grasp type, so the grasp type means different kinds of label grasps, so it make sense and can also prevent from one-to-one mapping problem. As the  grasp type not only provides a good initial grasp but also helps to maintain a human-like hand pose when fingers contact the objects under the guidance of touchcode.

**Comment by ysyf293** [comment]
Thank you very much for your reply.For the third question, that is, there are multiple grasp types for each object, right? Is the label_grasps in the "0.002_s420_465-100_ex-True_seg-True_train_record-is111111-new_withlabelgrasp-expanded-100-unsampled.pkl" file I downloaded its corresponding grasp type lable?
In addition, there is a new question, I want to know what the path corresponding to object_dir, grasp_dir,objectEX_dir and object_lable_dir in the figure below refers to? I can't find it in the code you provided.
![image](https://github.com/hjlllll/Functionalgrasp/assets/144201362/1e94e91a-985b-40f5-bebb-2e31a2da515a)
I'm sorry to bother you so much, but your work is excellent, and I would love to know the details.

**Comment by hjlllll** [comment]
yes, each object labeled with multiple grasp types, 33 grasp types are in dir : data/33types, and second is these paths are not used as you can see in the code, so we just forget to delete it, sorry for that.

**Comment by ysyf293** [comment]
Thank you for your patient reply!

--------------原始邮件--------------
发件人："hjlllll ***@***.***&gt;;
发送时间：2023年10月8日(星期天) 上午10:22
收件人："hjlllll/Functionalgrasp" ***@***.***&gt;;
抄送："杨凡 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [hjlllll/Functionalgrasp] grasptype data (Issue #1)
-----------------------------------

 

 
yes, each object labeled with multiple grasp types, 33 grasp types are in dir : data/33types, and second is these paths are not used as you can see in the code, so we just forget to delete it, sorry for that.

**Comment by hjlllll** [comment]
yeah and thanks for interested in our work
