### ISSUE TITLE
Does this system have high hardware requirements?

### ISSUE THREAD

**Issue by ccmCCMfk** [hjlllll/Functionalgrasp#2]
Thanks for your great work!Amazing!I want to ask if it is possible to run this project in simulation with a computer of GPU Quadro P2000:
Pascal GPU 
1024 NVIDIA® CUDA® Cores
5 GB GDDR5 CPU Memory
Up to 140GB/s Memory Bandwidth
PCI Express 3.0 System Interface
I know Issac gym is running on the gpu.

**Comment by ccmCCMfk** [comment]
I'm worried that the GPU memory isn't enough .

**Comment by hjlllll** [comment]
hi, thanks for your interest, I can tell you our computer settings which is NVIDIA RTX2080Ti with 11 GB GPU memory and Intel 11 series CPU, and isaacgym can run on cpu too.

**Comment by ccmCCMfk** [comment]
Thanks for reaching out,and I'm wondering if it is OK to train the model through a remote server,and visulize the result on local computer.

**Comment by ccmCCMfk** [comment]
Thanks for reaching out,I will have a try.

**Comment by ccmCCMfk** [comment]
I install Graspit successfully,but I want to ask about how to install Toward-Human-Like-Grasp and Pointnet/Pointnet++,I install the packages of KCPconv in Toward-Human-Like-Grasp,I tried https://github.com/yanx27/Pointnet_Pointnet2_pytorch.git,but it didn't work.

**Comment by ccmCCMfk** [comment]
I install Graspit successfully,but I want to ask about how to install Toward-Human-Like-Grasp and Pointnet/Pointnet++,I install the packages of KCPconv in Toward-Human-Like-Grasp,I tried "pip install git+https://github.com/yanx27/Pointnet_Pointnet2_pytorch.git",but it didn't work.

**Comment by hjlllll** [comment]
hi, only pip may not work, follow the pointnet_pytorch installation, download the module and then pip install -e. to compile the c++ code

**Comment by ccmCCMfk** [comment]
and I also want to make sure that  does "install Towad-Human-Like-Grasp" mean to install the packages in that environment,since the setup.py in that project is absent and the needed python file is already in this Project.Thanks a lot for your patient reply.
