### ISSUE TITLE
questions about mano folder

### ISSUE THREAD

**Issue by ccmCCMfk** [hjlllll/Functionalgrasp#3]
When I try to run map_to_shadow.py,it can't find the mano.mano_m.utils module，so I install mano with pip install git+https://github.com/hassony2/MANO.git,and change from mano.mano_m.utils import Mesh to from mano.utils import Mesh,the result is a fugure,I'm wondering that is it ok to do so?and how did you get that module?The mano link under the project page is invalid now:400: Invalid request

**Comment by ccmCCMfk** [comment]
Now I'm training the classification network,but when I train the ik model,it trun out that  "No handles with labels found to put in legend" without an error,I don't know the reason.

By the way,I found that maybe the device in function "run" of FK_model.py misspelled,RuntimeError: Expected all tensors to be on the same device, but found at least two devices cpu and gpu,I replace "self.device = base.device" with "self.device = torch.device("cuda")",it works.

**Comment by hjlllll** [comment]
hi, just follow the official mano installation will be fine and thanks for the device stuff, may be it is different on various device

**Comment by ysyf293** [comment]
> When I try to run map_to_shadow.py,it can't find the mano.mano_m.utils module，so I install mano with pip install git+https://github.com/hassony2/MANO.git,and change from mano.mano_m.utils import Mesh to from mano.utils import Mesh,the result is a fugure,I'm wondering that is it ok to do so?and how did you get that module?The mano link under the project page is invalid now:400: Invalid request

I met the same problem, how did you solve "No module named 'mano.mano_m'"?

**Comment by hjlllll** [comment]
I uploaded the mano_m, hope it helped!

**Comment by ysyf293** [comment]
Thank you very much. I would like to ask again, how are these beautiful segmentation pictures in the paper `visualized?`
<img width="362" alt="微信图片_20231028232127" src="https://github.com/hjlllll/Functionalgrasp/assets/144201362/810434ec-1c43-48c1-8590-c4f8f89cbf38">
``
