### ISSUE TITLE
About dataset information

### ISSUE THREAD

**Issue by ccmCCMfk** [hjlllll/Functionalgrasp#5]
Sorry to bother you,in train_GraspNet.py,maybe the files below are missed?
# dataset imformation
    object_dir = r'/home/lm/Documents/ddg_data/grasp_dataset/good_shapes'
    grasp_dir = r'/home/lm/Documents/ddg_data/grasp_dataset/grasps'
    objectEX_dir = r'../Data/expand_all'
    object_label_dir = r'../Data/labeled_data2/use'
    print(object_label_dir)

**Comment by hjlllll** [comment]
leave it, not used, deleted.

**Comment by ccmCCMfk** [comment]
Thank you very mach,I will have a try.

**Comment by ccmCCMfk** [comment]
I tried to debug the program in the afternoon, but a lot of errors were reported, maybe it's because GraspNet.py has many connections with train_GraspNet.py,I don't know how to solve it cause there are too many files to rectify,and it seems that dataset 'val set','test set','new set' are missed in use folder,I found that they were used in the train_GraspNet.py.

**Comment by hjlllll** [comment]
sorry the "test" and "new" we don't use them as you can see in the code. The "val" is for test in our dataset. if you want test your own object,  "test" and "new" will be used. The code is based on previous work human-like grasp, you can check the codes together for better understanding, and the environment is kind of difficult and codes is a little bit large, so be patient.

**Comment by ccmCCMfk** [comment]
Thank you very much,I will run this project to see if there is something to do the next week.And I'm wondering that should all the code related with the above dataset information in the GraspNet.py be deleted?

**Comment by ccmCCMfk** [comment]
Thanks for your help,now it runs successfully,but is seems that the val set is missed,I don't know where to download the 0.002_s420_465-100_ex-True_seg-True_train_record-is111111-new_one_grasptype20220118_downsampled_addhandpoints_normals.pkl.Or the val set is part of the train set,so just choose the same .pkl file?

**Comment by ysyf293** [comment]
> Thanks for your help,now it runs successfully,but is seems that the val set is missed,I don't know where to download the 0.002_s420_465-100_ex-True_seg-True_train_record-is111111-new_one_grasptype20220118_downsampled_addhandpoints_normals.pkl.Or the val set is part of the train set,so just choose the same .pkl file?

I have the same problem. Have you solved it
