### ISSUE TITLE
questions about visulizing and how to integrate issacgym and graspit in the ros system 

### ISSUE THREAD

**Issue by ccmCCMfk** [hjlllll/Functionalgrasp#6]
Thanks for your great work,I solved many problems,and got the xml results,but I can't find the robot.xml(our_hand.xml) and graspableBody.xml(they are in good_shapes folder),also I have strong interest in how to integrate issacgym and graspit in the ros system and how to control the arm-hand system,but our group has a very weak foundation in this area,so if possible,hoping to communicate more with you,I a student from ustc,China,my email is chenchangmao@mail.ustc.edu.cn and wechat is c18845636629.Looking forward to your reply!

**Comment by ysyf293** [comment]
> Thanks for your great work,I solved many problems,and got the xml results,but I can't find the robot.xml(our_hand.xml) and graspableBody.xml(they are in good_shapes folder),also I have strong interest in how to integrate issacgym and graspit in the ros system and how to control the arm-hand system,but our group has a very weak foundation in this area,so if possible,hoping to communicate more with you,I a student from ustc,China,my email is [chenchangmao@mail.ustc.edu.cn](mailto:chenchangmao@mail.ustc.edu.cn) and wechat is c18845636629.Looking forward to your reply!

I have the same problem. Have you solved it? Could you tell us the solution

**Comment by ccmCCMfk** [comment]
Actually, I only have a theoretically feasible technical route now, but I haven't started to put it into practice yet.

**Comment by ccmCCMfk** [comment]
I plan to do this in the future, but this part of issacgym is just an experimental verification, and I think the robot grasping algorithm is more important.
