### ISSUE TITLE
pre-training

### ISSUE THREAD

**Issue by ysyf293** [hjlllll/Functionalgrasp#8]
May I ask what is the difference between pre-training and normal training in the GraspNet code? What is the purpose of pre-training?

**Comment by hjlllll** [comment]
you can pre-train then train or directly train, we just found after pre-training only with labeled grasp, network perform better.

**Comment by ysyf293** [comment]
I got it. Thank you very much for your time.

--------------原始邮件--------------
发件人："hjlllll ***@***.***&gt;;
发送时间：2023年11月7日(星期二) 晚上8:17
收件人："hjlllll/Functionalgrasp" ***@***.***&gt;;
抄送："杨凡 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [hjlllll/Functionalgrasp] pre-training (Issue #8)
-----------------------------------

 

 
you can pre-train or directly, we just found after pre-training only with labeled grasp, network perform better.
